spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false #开发阶段false可以， 正式环境中建议启用自我保护模式
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，职责是维护实例，不参加检索
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置eureka server的交互地址，即对外暴露的地址
---
spring:
  profiles: test
server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false #开发阶段false可以， 正式环境中建议启用自我保护模式
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，职责是维护实例，不参加检索
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置eureka server的交互地址，即对外暴露的地址