spring:
 profiles:
   active:
     - dev
---
spring:
 profiles: dev
 application:
   name: hf-itheima-cloud-eureka-configclient-dev
server:
port: 7001
eureka:
instance:
 hostname: eureka01   #hostname为hosts文件中映射的地址
client:
 register-with-eureka: false   #false表示不向注册中心注册自己
 fetch-registry: false      #false表示自己就是注册中心，职责是维护实例，不参加检索
 service-url:
  defaultZone: http://eureka01:7001/eureka/  #设置eureka server的交互地址
---
spring:
 profiles: test
 application:
   name: hf-itheima-cloud-eureka-configclient-test
server:
port: 7001
eureka:
instance:
 hostname: eureka7002   #hostname为hosts文件中映射的地址
client:
 register-with-eureka: false   #false表示不向注册中心注册自己
 fetch-registry: false      #false表示自己就是注册中心，职责是维护实例，不参加检索
 service-url:
  defaultZone: http://eureka7002:7002/eureka/   #设置eureka server的交互地址
