spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml # mybatis配置文件所在路径
  type-aliases-package: com.itheima.springcloud.pojo # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/*.xml # mapper映射文件
spring:
  profiles: dev
  application:
    name: hf-itheima-cloud-provider # 注意不能修改 千万不要写下划线
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?characterEncoding=utf-8 #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7001/eureka
  instance:
    instance-id: hf_itheima_cloud_provider:8001 #修改别名
    prefer-ip-address: true #显示IP地址
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml # mybatis配置文件所在路径
  type-aliases-package: com.itheima.springcloud.pojo # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/*.xml # mapper映射文件
spring:
  profiles: test
  application:
    name: hf-itheima-cloud-provider # 注意不能修改 千万不要写下划线
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02?characterEncoding=utf-8 #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7001/eureka
  instance:
    instance-id: hf_itheima_cloud_provider:8001 #修改别名
    prefer-ip-address: true #显示IP地址